//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.IControladorServicio")]
    public interface IControladorServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/ValidarUsuario", ReplyAction="http://tempuri.org/IControladorServicio/ValidarUsuarioResponse")]
        string ValidarUsuario(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarUsuario", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarUsuarioResponse")]
        string RecuperarUsuario(string run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RegistrarUsuario", ReplyAction="http://tempuri.org/IControladorServicio/RegistrarUsuarioResponse")]
        string RegistrarUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RegistrarUsuarioDesdeAdmin", ReplyAction="http://tempuri.org/IControladorServicio/RegistrarUsuarioDesdeAdminResponse")]
        string RegistrarUsuarioDesdeAdmin(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/EliminarUsuario", ReplyAction="http://tempuri.org/IControladorServicio/EliminarUsuarioResponse")]
        string EliminarUsuario(string run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarUsuario_Todos", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarUsuario_TodosResponse")]
        string RecuperarUsuario_Todos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/ListarComprasUsuario", ReplyAction="http://tempuri.org/IControladorServicio/ListarComprasUsuarioResponse")]
        string ListarComprasUsuario(string run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarOrganizacion_RUT", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarOrganizacion_RUTResponse")]
        string RecuperarOrganizacion_RUT(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarOrganizacion_RUN", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarOrganizacion_RUNResponse")]
        string RecuperarOrganizacion_RUN(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/DesactivarOrganizacion", ReplyAction="http://tempuri.org/IControladorServicio/DesactivarOrganizacionResponse")]
        string DesactivarOrganizacion(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/ModificarOrganizacion", ReplyAction="http://tempuri.org/IControladorServicio/ModificarOrganizacionResponse")]
        string ModificarOrganizacion(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/EliminarEvento", ReplyAction="http://tempuri.org/IControladorServicio/EliminarEventoResponse")]
        string EliminarEvento(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarEvento_Codigo", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarEvento_CodigoResponse")]
        string RecuperarEvento_Codigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarEventos_Organizacion", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarEventos_OrganizacionResponse")]
        string RecuperarEventos_Organizacion(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarEventos_UltimosEventos", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarEventos_UltimosEventosResponse")]
        string RecuperarEventos_UltimosEventos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/ListarEventos_Activos", ReplyAction="http://tempuri.org/IControladorServicio/ListarEventos_ActivosResponse")]
        string ListarEventos_Activos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RegistrarEvento", ReplyAction="http://tempuri.org/IControladorServicio/RegistrarEventoResponse")]
        string RegistrarEvento(string evento, int cantidadMaxima, int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/ModificarEvento", ReplyAction="http://tempuri.org/IControladorServicio/ModificarEventoResponse")]
        string ModificarEvento(string evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarRecinto_Codigo", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarRecinto_CodigoResponse")]
        string RecuperarRecinto_Codigo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarRecinto_Todos", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarRecinto_TodosResponse")]
        string RecuperarRecinto_Todos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarTipo_Eventos", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarTipo_EventosResponse")]
        string RecuperarTipo_Eventos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarTipo_Usuarios", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarTipo_UsuariosResponse")]
        string RecuperarTipo_Usuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarEntradas", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarEntradasResponse")]
        string RecuperarEntradas(string cadena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControladorServicioChannel : Vista.Servicio.IControladorServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControladorServicioClient : System.ServiceModel.ClientBase<Vista.Servicio.IControladorServicio>, Vista.Servicio.IControladorServicio {
        
        public ControladorServicioClient() {
        }
        
        public ControladorServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControladorServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControladorServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControladorServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidarUsuario(string usuario, string contrasena) {
            return base.Channel.ValidarUsuario(usuario, contrasena);
        }
        
        public string RecuperarUsuario(string run) {
            return base.Channel.RecuperarUsuario(run);
        }
        
        public string RegistrarUsuario(string usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public string RegistrarUsuarioDesdeAdmin(string usuario) {
            return base.Channel.RegistrarUsuarioDesdeAdmin(usuario);
        }
        
        public string EliminarUsuario(string run) {
            return base.Channel.EliminarUsuario(run);
        }
        
        public string RecuperarUsuario_Todos() {
            return base.Channel.RecuperarUsuario_Todos();
        }
        
        public string ListarComprasUsuario(string run) {
            return base.Channel.ListarComprasUsuario(run);
        }
        
        public string RecuperarOrganizacion_RUT(string rut) {
            return base.Channel.RecuperarOrganizacion_RUT(rut);
        }
        
        public string RecuperarOrganizacion_RUN(string rut) {
            return base.Channel.RecuperarOrganizacion_RUN(rut);
        }
        
        public string DesactivarOrganizacion(string rut) {
            return base.Channel.DesactivarOrganizacion(rut);
        }
        
        public string ModificarOrganizacion(string rut) {
            return base.Channel.ModificarOrganizacion(rut);
        }
        
        public string EliminarEvento(string codigo) {
            return base.Channel.EliminarEvento(codigo);
        }
        
        public string RecuperarEvento_Codigo(string codigo) {
            return base.Channel.RecuperarEvento_Codigo(codigo);
        }
        
        public string RecuperarEventos_Organizacion(string rut) {
            return base.Channel.RecuperarEventos_Organizacion(rut);
        }
        
        public string RecuperarEventos_UltimosEventos() {
            return base.Channel.RecuperarEventos_UltimosEventos();
        }
        
        public string ListarEventos_Activos() {
            return base.Channel.ListarEventos_Activos();
        }
        
        public string RegistrarEvento(string evento, int cantidadMaxima, int valor) {
            return base.Channel.RegistrarEvento(evento, cantidadMaxima, valor);
        }
        
        public string ModificarEvento(string evento) {
            return base.Channel.ModificarEvento(evento);
        }
        
        public string RecuperarRecinto_Codigo(int codigo) {
            return base.Channel.RecuperarRecinto_Codigo(codigo);
        }
        
        public string RecuperarRecinto_Todos() {
            return base.Channel.RecuperarRecinto_Todos();
        }
        
        public string RecuperarTipo_Eventos() {
            return base.Channel.RecuperarTipo_Eventos();
        }
        
        public string RecuperarTipo_Usuarios() {
            return base.Channel.RecuperarTipo_Usuarios();
        }
        
        public string RecuperarEntradas(string cadena) {
            return base.Channel.RecuperarEntradas(cadena);
        }
    }
}
