//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.IControladorServicio")]
    public interface IControladorServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/ValidarUsuario", ReplyAction="http://tempuri.org/IControladorServicio/ValidarUsuarioResponse")]
        string ValidarUsuario(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RecuperarUsuario", ReplyAction="http://tempuri.org/IControladorServicio/RecuperarUsuarioResponse")]
        string RecuperarUsuario(string run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RegistrarUsuario", ReplyAction="http://tempuri.org/IControladorServicio/RegistrarUsuarioResponse")]
        string RegistrarUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorServicio/RegistrarUsuarioDesdeAdmin", ReplyAction="http://tempuri.org/IControladorServicio/RegistrarUsuarioDesdeAdminResponse")]
        string RegistrarUsuarioDesdeAdmin(string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControladorServicioChannel : Vista.Servicio.IControladorServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControladorServicioClient : System.ServiceModel.ClientBase<Vista.Servicio.IControladorServicio>, Vista.Servicio.IControladorServicio {
        
        public ControladorServicioClient() {
        }
        
        public ControladorServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControladorServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControladorServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControladorServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidarUsuario(string usuario, string contrasena) {
            return base.Channel.ValidarUsuario(usuario, contrasena);
        }
        
        public string RecuperarUsuario(string run) {
            return base.Channel.RecuperarUsuario(run);
        }
        
        public string RegistrarUsuario(string usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public string RegistrarUsuarioDesdeAdmin(string usuario) {
            return base.Channel.RegistrarUsuarioDesdeAdmin(usuario);
        }
    }
}
